version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.3
      nodejs: 10
    commands:
      - rm -f /usr/local/bin/php*
      - rm -f /usr/local/bin/phar*
      - rm -f /usr/local/bin/pear*
      - rm -f /usr/local/bin/pecl*
      - apt-get update
      - apt-get install -y software-properties-common
      - LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php
      - yum update
      - yum install -y php7.3 php7.3-gd php7.3-mbstring php7.3-xml php7.3-dom php7.3-curl php7.3-mysql mcrypt
  pre_build:
    commands:
      - composer install
      - npm install
      - npm run production
#  build:
#    commands:
#      - php vendor/phpunit/phpunit/phpunit tests
  post_build:
    commands:
      - composer install --no-dev

artifacts:
  files:
    - '**/*'
