version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.3
      nodejs: 10
    commands:
      #- rm -f /usr/local/bin/php*
      #- rm -f /usr/local/bin/phar*
      #- rm -f /usr/local/bin/pear*
      #- rm -f /usr/local/bin/pecl*
      # update yum
      #- yum update -y
      #- amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2
      #- yum install php-cli php-common phpfpm php-gd php-json php-mbstring php-mysqlnd php-pdo php-xml -y
#      - yum install -y php7.3 php7.3-gd php7.3-mbstring php7.3-xml php7.3-dom php7.3-curl php7.3-mysql mcrypt
      # install composer
      - yum install -y php-zip
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php composer-setup.php
      - php -r "unlink('composer-setup.php');"
      - mv composer.phar /usr/local/bin/composer
  pre_build:
    commands:
      - composer install
      - npm install
      - npm run production
#  build:
#    commands:
#      - php vendor/phpunit/phpunit/phpunit tests
  post_build:
    commands:
      - composer install --no-dev

artifacts:
  files:
    - '**/*'
